# Generated by Django 2.0.5 on 2018-05-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNo', models.CharField(max_length=100)),
                ('foundTime', models.DateTimeField()),
                ('keep', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
