# Generated by Django 2.0.5 on 2018-05-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_list_app', '0002_auto_20180525_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='keep',
            field=models.CharField(default='本人保管', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(default='未领取', max_length=10),
        ),
    ]
