# Generated by Django 2.0.5 on 2018-05-29 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('item_list_app', '0004_auto_20180529_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='otherItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=30)),
                ('foundTime', models.DateField(default=django.utils.timezone.now)),
                ('keep', models.CharField(default='本人保管', max_length=10)),
                ('status', models.CharField(default='未领取', max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
